export default {
  USER_REGISTERED: "USER_REGISTERED",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  GET_TOP_HEADLINES_ALL: "GET_TOP_HEADLINES_ALL",
  ERROR_MESSAGE: "ERROR_MESSAGE",
  GET_SEARCH_RESULTS: "GET_SEARCH_RESULTS",
  GET_PROFILE: "GET_PROFILE",
  GET_BOOKMARKS: "GET_BOOKMARKS"
};